// Created with jtex v.1.0.21
#import "lapreprint.typ": *
#show: template.with(
  title: "Introduction to quality control with fastQC and multiQC",
  abstract: (
    (
      title: "Abstract",
      content: [
This training is a cornerstone of AVecGen's commitment to building sustainable capacity within Africa's scientific community. By integrating genomic tools into everyday vector control practices, participants will learn to analyse genetic data from disease vectors, interpret complex datasets, and apply insights to real-world decision-making. The program's purpose is to bridge the gap between emerging technologies and on-the-ground public health needs, fostering a multidisciplinary workforce that can tackle Africa's unique epidemiological challenges. In an era where climate change and urbanisation are amplifying vector threats, this training is more urgent than ever, it will empower young scientists to develop targeted interventions, reduce disease transmission, and save lives through quality research. We invite dedicated scientists and practitioners to join this transformative effort and contribute to a healthier Africa.
      ]
    ),
  ),
  date: datetime(
    year: 2026,
    month: 7,
    day: 3,
  ),
  keywords: ("AVecGen","Bioinformatics","Genomics","CRID","Cameroon",),
  authors: (
    (
      name: "Dr. Gadji M.",
      affiliations: "1",
    ),
    (
      name: "Tepa Arnaud",
      affiliations: "1",
    ),
    (
      name: "Tazokong Hervé Raoul",
      affiliations: "1",
    ),
    (
      name: "Cedrique Noutchih",
      affiliations: "1",
    ),
  ),
  affiliations: (
    (
      id: "1",
      name: "Centre de Recherche sur les Maladies Infectieuses (CRID), Yaoundé, Cameroon",
    ),
  ),
  margin: (
  ),
)

#import "myst-imports.typ": *

/* Written by MyST v1.9.0 */

== Introduction to quality control with `fastQC` and `multiQC` <introduction-to-quality-control-with-fastqc-and-multiqc>

#link("https://www.bioinformatics.babraham.ac.uk/projects/fastqc/")[FastQC] and #link("https://seqera.io/multiqc/")[MultiQC] are the industry-standard tools for assessing and visualising the quality of raw high-throughput sequencing (NGS) data (e.g., FASTQ, BAM, or SAM files). FastQC generates detailed QC reports for individual files, while MultiQC aggregates these metrics into a single, interactive, and comprehensive dashboard.

Here is an overview of how these tools work together and what to look for in your analysis:
= 1. The Core Tool: FastQC <id-1-the-core-tool-fastqc>

FastQC evaluates raw sequence data across ten distinct modules, providing a quick assessment *(Pass/Warning/Fail)* for metrics such as:

- _Per Base Sequence Quality_: Checks if the sequencing quality scores (Phred scores) remain high across the entire length of the read.
- _Sequence Duplication Levels_: Helps identify potential PCR over-amplification or low-complexity libraries.
- _Adapter Content_: Alerts you if raw sequencing adapters have not been fully trimmed from the ends of the reads.

== Basic Usage <basic-usage>

To run FastQC on a single or multiple FASTQ files, use the following terminal command:

```bash
fastqc read1_R1.fq.qz read1_R2.fq.qz
```

#tipBlock[
You can use `fastqc *.fq.gz` to process every file in your directory automatically or you can use loops to iterate into each file and process all fastq files with the extension `.fq.gz`.
]

```bash
for i in sample /path/to/fastq/reads/ ; do fastqc '$i' -o /path/to/fastqc/output;
done
```

Below we are presenting a figure showing the final output from fastQC run.

#show figure: set block(breakable: breakableDefault)
#figure(
  image("files/fastqc.output-0f8130a36e6d68b3dec5b3db7dc4cbc9.png", width: 90%),
  caption: [
Fig 1. Fastqc output.
],
  kind: "figure",
  supplement: [Figure],
)

= 2. The Aggregator: MultiQC <id-2-the-aggregator-multiqc>

Reviewing dozens or hundreds of individual FastQC HTML reports is tedious. MultiQC solves this by scanning your results directory, extracting the metadata and statistics, and compiling them into a single streamlined HTML file that is easy to share and interpret.
== Basic Usage

To use MultiQC, simply navigate to the folder containing your FastQC output files and run:

```bash
multiqc . -o path/to/multiqc/output
```

We are presenting below the aggregated QC figure generated by `multiQC`

#show figure: set block(breakable: breakableDefault)
#figure(
  image("files/multiqc.output.figur-fda42d3117f364b589a319fd5bb576e1.png", width: 90%),
  caption: [
Fig 2. Multiqc output
],
  kind: "figure",
  supplement: [Figure],
)

= Bonus <bonus>

Key Metrics to Monitor When reviewing your MultiQC report, pay close attention to these common warning signs:
- \*Sequence Length Distribution\*: If reads vary heavily in length, you may need to trim low-quality sequences or adapter fragments using a tool like \[Trim Galore\](https://www.bioinformatics.babraham.ac.uk/projects/trim\_galore/) or \[fastp\](https://github.com/opengene/fastp).

- _Per Sequence Quality Scores_: A significant drop in quality toward the 3' end of the reads is common in Illumina sequencing. If the average score drops below 20 (indicating a 1% probability of an incorrect base call), trimming is necessary.
- _Overrepresented Sequences_: This usually indicates either adapter dimers or highly abundant transcripts (e.g., ribosomal RNA in RNA-Seq).

Additional parameters should be taken into account depending on the type of genomic data you are dealing with.
